export const BASE_URL = import.meta.env.VITE_BACKEND_URL ?? "http://localhost:8080";

/*
    BASE_URL = É UMA CONSTANTE QUE POR PADRÃO PEGA O OPERADOR DE COALESCÊNCIA "??".

    ?? = OPERADOR DE COALESCÊNCIA NULA. O QUE SIGINIFICA?
         DO LADO DIRETO TEMOS "http://localhost:8080" QUE É O VALOR PADRÃO DA VARIÁVEL. PORÉM ELA TEM
         POR ALTERNATIVAMENTE O VALOR PEGO DA VARIÁVEL DE AMBIENTE QUE ESTÁ DO LADO
         ESQUERDO "import.meta.env.VITE_BACKEND_URL"
*/